update to editable components v2.x, react 18.x
adobe/aem-guides-wknd-graphql pull request #73
Opened 2022-09-14 16:20 UTC by hannessolo

Updates the dependencies to aem-react-editable-components v2.x and react 18.x. 

## Description

Also removes the dependency on aem-react-core-wcm-components, as this is being deprecated.

## Related Issue

Internal: [SITES-7938](https://jira.corp.adobe.com/browse/SITES-7938)

## Motivation and Context

## How Has This Been Tested?

Tested by ensuring the website still runs both standalone and in the editor.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-09-14 16:20 UTC, hannessolo commented on react-app/config-overrides.js
> +module.exports = function override(config, env) {
This file is currently necessary because aem-react-editable-components is not built for ES6. See https://github.com/adobe/aem-react-editable-components/pull/134 and https://github.com/adobe/aem-react-editable-components/issues/133

2022-10-27 16:08 UTC, davidjgonzalez requested changes
Can you add comments to some of these "utility functions" that explain why youre creating them, and why you should maintain them (vs. having them in the Editable Components v2 SDK?)

2022-10-27 16:08 UTC, davidjgonzalez commented on react-app/src/components/editable/core/util/withStandardBaseCssClass.js
> +import React from 'react'
Can you add comments as to what this does and why its important?

2022-10-27 16:08 UTC, davidjgonzalez commented on react-app/src/components/editable/core/util/withConditionalPlaceholder.js
> +import React from 'react'
Can you add comments as to what this does and why its important?

2022-10-27 16:08 UTC, davidjgonzalez commented on react-app/src/components/editable/core/util/EditorPlaceholder.js
> +import React from 'react';
Can you add comments as to what this does and why its important?

2022-10-27 16:12 UTC, davidjgonzalez commented on react-app/src/components/editable/core/RoutedLink.js
> +export const RoutedLink = (props) => {
Should we add a comment here (and/or previous file) talking about the concern of RoutedLinks? IIRC in the past we've not used really used editable routed links since the Core Componetns Dialogs use path pickers that encourage an author to select a CQ Page resource (and there is no autocomplete or anything to SPA routes)

2022-10-28 09:58 UTC, hannessolo commented
> vs. having them in the Editable Components v2 SDK

It was decided that we no longer want to maintain the react implementations of core components, which is why all these components and utilities are now just provided as a starting point in the example code.

I will add some comments explaining what they do.

2022-10-28 10:34 UTC, hannessolo commented on react-app/src/components/editable/core/RoutedLink.js
> +export const RoutedLink = (props) => {
Should we just remove the file? Afaik it isn't actually used in the example content

2022-10-28 10:39 UTC, hannessolo commented on react-app/src/components/editable/core/RoutedLink.js
> +export const RoutedLink = (props) => {
The routed link in this case is only included because the Image and Title components (which I adapted from the old react core components) use it internally. Its not exposed as an editable component. 

But I see how it could be confusing. I will add a comment to explicitly discourage people making the routed link editable.

2022-11-01 15:07 UTC, merged